const Details=
[
    {type:"pre",image:"https://i.ibb.co/9G4kKbG/76958636-3440291345996056-2836842490466664448-n.jpg",eventname:"Group-Extempore",aboutevent:"Event Short details",img1:"https://i.ibb.co/2qHgvgs/Screenshot-2020-08-13-21-16-26-775-com-google-android-googlequicksearchbox.jpg" ,
    detail:"Stage fear,lack of team coordination, inefficiency in speaking to the point etc. are the characteristics of unprofessional group presentations. In fact these together define the word<br> under confident.<br>So to boost the self-confidence of the students, this group Extempore was organised.<br>The participants were supposed to form teams consisting of 3 members, a challenging<br>topic was given to each team. One of the members had to speak in favour of the given<br>topic, 2nd member in against and the last member was supposed to suggest<br>a solution for a given condition based on the other two team members views.",
    category:"Extempore",time:"11th November 2019",title:"On the occasion of National Education Day,the Literary Club of IIT Jammu had arranged a Group Extempore ",hostman:"Unknown"}
    ,
    {type:"pre",image:"https://i.ibb.co/zs3G0kd/IMG-20200810-192258.jpg",eventname:"Short Fiction Story Writing",aboutevent:"Event Short details",img1:"https://i.ibb.co/zm1xvvX/IMG-20200808-180632.jpg" ,detail:"History might be a boring subject for many, but the rest have an immense interest in this not much liked subject. Often our imagination takes us to those battle grounds, those prisons, courts etc. This contest had given the opportunity to introduce an imaginary character in any of the  historical events, but the twist was: The ending must remain the same..!This contest witnessed high participation. It was a pan India contest so writers from different parts of India had participated in this.",category:"Pan India Story Writing",time:"13th June-9th July ",title:"A pan India Story writing contest was organised.",hostman:"Unknown"}
    ,
    {type:"pre",image:"https://i.ibb.co/CmmDDVM/83501579-784010288779241-8591710277509054464-n.jpg",eventname:"Group Discussion",aboutevent:" A healthy Group Discussion on “Should Higher Education be made free in India?”  was held on our Republic day. ",img1:"https://i.ibb.co/JKC213q/Screenshot-2020-08-08-17-53-50-289-com-instagram-android.jpg" ,detail:"Details - Updated all the third party vendor libraries to their latest versions- Other small fixes and improvements",category:"Group Discussion",time:"26th January 2020",title:"The participants were from various states and had experienced different educational boards. On the basis of their experiences, everyone had proposed their opinions very pertinently. Talking about the pros and cons of free higher education the points raised in the discussion covered various factors affecting this. The effects of this on various income groups: Upper Class, Middle Class and lower class were discussed. A comparison between the educational system of India and of the other countries was made, this was very informative.",hostman:"Unknown"}
    ,
    {type:"pre",image:"https://i.ibb.co/hgnLrHX/Roastbrief-Los-blogs-jam-s-pasaron-de-moda.jpg" ,eventname:"Blog Writing" ,aboutevent:"Short details",img1:"https://i.ibb.co/7KWLsgj/IMG-20200808-180653.jpg" ,detail:"The Coronavirus Lockdown served as an Enlightener for numerous. Those days when everyone was free to do anything Remaining In Their Homes, had taught everyone one or the other thing. This competition aimed at giving a chance to  the participants to Share their lockdown achievements be it minute or significant and to introduce the world “ Their New Version”.The writers were supposed to express their lockdown story in the form of a blog.",category:"Blog comp",time:"6th May-8th May",title:"Title part",hostman:"Unknown"}
    ,
    {type:"pre",image:"http://www.shapeyourculture.org.uk/wp-content/uploads/2014/06/Vector-Icons-for-challenges-new-241.png",eventname:"Picture-Story-Writing",aboutevent:"Event Short details",img1:"https://i.ibb.co/StcLkmT/IMG-20200808-180606.jpg",detail:"Stories are a significant part of many childhoods.<br>What if someone asks us to draft a story! Okay, let’s make this a bit more challenging; What if someone gives us a group of pictures, asking to frame a story using them as a part of our story! This was the basic theme of this Picture-Story writing contest. <br>The most interesting part: Every participant was provided with the same pictures.. So many different stories! Every story had distinct emotions, characters yet had their own charm.<br><br> ",category:"Picture Story Writing",time:"22nd May-26th May",title:"Title part",hostman:"Unknown"}
    


];
export default Details;