const Details=
[
    {type:"pre",image:"https://picsum.photos/400/400?grayscale",eventname:"Eventname-1",aboutevent:"Event Short details",img1:"https://picsum.photos/800/1100",detail:"Details:- Updated all the t:ird party vendor libraries to their latest versions- Other small fixes and improvements",platform:"www.codeforce.com",category:"Blog comp",time:"31 Jan,2020",title:"Title part" ,hostman:"Unknown"},
    {type:"pre",image:"https://picsum.photos/400/400?grayscale",eventname:"Eventname-2",aboutevent:"Event Short details",img1:"https://picsum.photos/800/1100" ,detail:"Details - Updated all the third party vendor libraries to their latest versions- Other small fixes and improvements",platform:"www.codeforce.com",category:"Blog comp",time:"31 Jan,2020",title:"Title part",hostman:"Unknown"},
    {type:"pre",image:"https://picsum.photos/400/400?grayscale",eventname:"Eventname-3",aboutevent:"Event Short details",img1:"https://picsum.photos/800/1100" ,detail:"Details - Updated all the third party vendor libraries to their latest versions- Other small fixes and improvements",platform:"www.codeforce.com",category:"Blog comp",time:"31 Jan,2020",title:"Title part",hostman:"Unknown"},
    {type:"up",image:"https://picsum.photos/400/400?grayscale",eventname:"Eventname-4",aboutevent:"Event Short details",img1:"https://picsum.photos/800/1100" ,detail:"Details - Updated all the third party vendor libraries to their latest versions- Other small fixes and improvements",platform:"www.codeforce.com",category:"Blog comp",time:"31 Jan,2020",title:"Title part",hostman:"Unknown"},
    {type:"up",image:"https://picsum.photos/400/400?grayscale",eventname:"Eventname-5",aboutevent:"Event Short details",img1:"https://picsum.photos/800/1100" ,detail:"Details - Updated all the third party vendor libraries to their latest versions- Other small fixes and improvements",platform:"www.codeforce.com",category:"Blog comp",time:"31 Jan,2020",title:"Title part",hostman:"Unknown"},
    {type:"up",image:"https://picsum.photos/400/400?grayscale",eventname:"Eventname-6",aboutevent:"Event Short details",img1:"https://picsum.photos/800/1100" ,detail:"Details - Updated all the third party vendor libraries to their latest versions- Other small fixes and improvements",platform:"www.codeforce.com",category:"Blog comp",time:"31 Jan,2020",title:"Title part",hostman:"Unknown"}
];
export default Details;