const Details=
[
    {o:"",oo:"",ooo:"",first:"",second:"",third:"",index:"1",type:"pre",image:"https://i.ibb.co/9G4kKbG/76958636-3440291345996056-2836842490466664448-n.jpg",eventname:"Group-Extempore",aboutevent:"",img1:"https://i.ibb.co/9G4kKbG/76958636-3440291345996056-2836842490466664448-n.jpg" ,
    detail:"Stage fear,lack of team coordination, inefficiency in speaking to the point etc. are the characteristics of unprofessional group presentations. In fact these together define the word under confident.So to boost the self-confidence of the students, this group Extempore was organised.The participants were supposed to form teams consisting of 3 members, a challenging topic was given to each team. One of the members had to speak in favour of the given topic, 2nd member in against and the last member was supposed to suggest a solution for a given condition based on the other two team members views.",
    category:"Extempore",time:"11th November 2019",title:"On the occasion of National Education Day,the Literary Club of IIT Jammu had arranged a Group Extempore ",hostman:"Prashant K. Sagar",platform:"College Premises"}
    ,
    {o:"https://drive.google.com/file/d/1V9B8MzzGM43ysY94nDEfWGquDtFunjov/view",oo:"https://drive.google.com/file/d/1NjaTjSpA5rwP7mWSel5H0T-9BLUVPjAD/view?usp=sharing",ooo:"https://drive.google.com/file/d/1ttPyiQCY1Q5V_Tn7bBbg6IsaRTJ4VxF_/view?usp=sharing",first:"Megha",second:"Prachi Kashikar",third:"Debashrita",index:"2",type:"pre",image:"https://i.ibb.co/zs3G0kd/IMG-20200810-192258.jpg",eventname:"Short Fiction Story Writing",aboutevent:"",img1:"https://i.ibb.co/zm1xvvX/IMG-20200808-180632.jpg" ,detail:"History might be a boring subject for many, but the rest have an immense interest in this not much liked subject. Often our imagination takes us to those battle grounds, those prisons, courts etc. This contest had given the opportunity to introduce an imaginary character in any of the  historical events, but the twist was: The ending must remain the same..!This contest witnessed high participation. It was a pan India contest so writers from different parts of India had participated in this.",category:"Pan India Story Writing",time:"13th June-9th July ",title:"A pan India Story writing contest was organised.",hostman:"Prashant Kumar Sagar and Shaivya Yadav",platform:"Online Event"}
    ,
    {first:"",second:"",third:"",index:"3",type:"pre",image:"https://i.ibb.co/CmmDDVM/83501579-784010288779241-8591710277509054464-n.jpg",eventname:"Group Discussion",aboutevent:" A healthy Group Discussion on “Should Higher Education be made free in India?”  was held on our Republic day. ",img1:"https://i.ibb.co/JKC213q/Screenshot-2020-08-08-17-53-50-289-com-instagram-android.jpg" ,title:"",category:"Group Discussion",time:"26th January 2020",detail:"The participants were from various states and had experienced different educational boards. On the basis of their experiences, everyone had proposed their opinions very pertinently. Talking about the pros and cons of free higher education the points raised in the discussion covered various factors affecting this. The effects of this on various income groups: Upper Class, Middle Class and lower class were discussed. A comparison between the educational system of India and of the other countries was made, this was very informative.",hostman:"Group Event",platform:"College Premises"}
    ,
    {first:"Yash Jain",o:"https://silenspeaking.wordpress.com/2020/05/10/slowing-down/",oo:"https://shanism7.wordpress.com/",ooo:"https://abcdotgendotin.wordpress.com/2020/05/08/covid-19-boon-or-bane/",second:"Shantanu Singh",third:"Ravi Shankar",index:"4",type:"pre",image:"https://i.ibb.co/hgnLrHX/Roastbrief-Los-blogs-jam-s-pasaron-de-moda.jpg" ,eventname:"Blog Writing" ,aboutevent:"",img1:"https://i.ibb.co/7KWLsgj/IMG-20200808-180653.jpg" ,detail:"The Coronavirus Lockdown served as an Enlightener for numerous. Those days when everyone was free to do anything Remaining In Their Homes, had taught everyone one or the other thing. This competition aimed at giving a chance to  the participants to Share their lockdown achievements be it minute or significant and to introduce the world “ Their New Version”.The writers were supposed to express their lockdown story in the form of a blog.",category:"Blog comp",time:"6th May-8th May",title:"Express your Lockdown Story to the World!",hostman:"Prashant Kumar Sagar" ,judge:"Dr. Sayantan Mandal",platform:"Online Event"}
    ,
    {o:"https://drive.google.com/file/d/1Tjy37Mxlj9NAz780lfkIXKTHLOAXFmYF/view?fbclid=IwAR0L4Hqrux0XXd9YHW_ytCdzHgUg31mr0-rCDK11sk4bWJb-fCzpmujZcDY",oo:"https://drive.google.com/file/d/1v09nDfvgZTDUHSudfbPe-A6bJeo5DF8W/view?fbclid=IwAR380bh8piF-HE99mCZLTQkBlI1jFfnsOvjyAlsnhrjR_jVj8B-BPhPkECs",ooo:"https://drive.google.com/file/d/1CPQd2m2bjXJp6mSlnRaIl3FnTMdAB1A6/view?fbclid=IwAR2eWMYtxLWoPhcl2Vw4BjRmA6UOC3h7j7_IHK3i_FSn64SqKTHUTe3YOfg",first:"Paridhi Mayande",second:"Prarthana Tripathy",third:"Amol Jaggi",index:"5",type:"pre",image:"https://i.ibb.co/StcLkmT/IMG-20200808-180606.jpg",eventname:"Picture-Story-Writing",aboutevent:"",img1:"https://i.ibb.co/StcLkmT/IMG-20200808-180606.jpg",detail:"Stories are a significant part of many childhoods.What if someone asks us to draft a story! Okay, let’s make this a bit more challenging; What if someone gives us a group of pictures, asking to frame a story using them as a part of our story! This was the basic theme of this Picture-Story writing contest. The most interesting part: Every participant was provided with the same pictures.. So many different stories! Every story had distinct emotions, characters yet had their own charm. ",category:"Picture Story Writing",time:"22nd May-26th May",title:" ''A professional writer is an amateur who didn't quit'' ",hostman:"Anushka Agrawal",platform:"Online Event"}
    ,
    {o:"",oo:"",ooo:"",first:"",second:"",third:"",index:"6",type:"pre",image:"https://i.ibb.co/74KZTTq/DSC0993.jpg",eventname:"Creative Writing Competition ",aboutevent:"",img1:"https://i.ibb.co/FXHR2YV/DSC1023.jpg",detail:"A teacher, or a guru, is the person who acts as an overall developer of its pupils. In ancient times, parents used to send their children to Gurukul where they were taught about the various elements which comprise a meaningful life.As time passed, the way of teaching changed. Gurukuls transformed into schools. Books manifested themselves into computers. And full marks and a stable career became the only reasons to study. This deprived the students of practical knowledge, making them intelligent but not smart. A creative writing competition was organised on Teachers’ Day to give a platform to students to analyse and express their opinion on what is the ideal way to learn and teach.",category:"Creative Writing",time:"5th September 2019",title:" Teaching kids to count is good. But teaching them what counts is the Best. ",hostman:"Shaivya Yadav",platform:"College Premises"}
    ,
    {o:"",oo:"",ooo:"",first:"",second:"",third:"",index:"7",type:"up",image:"https://i.ibb.co/Y0d4ryg/Literary-Club-IIT-Jammu-Presents.png",eventname:"Kuch Kisse Kuch Kahania ",aboutevent:"",img1:"https://i.ibb.co/Y0d4ryg/Literary-Club-IIT-Jammu-Presents.png",detail:"We think in pictures, not in words.Those pictures when take the form of words and are carved on to a plain sheet, it creates magic. Those words then go forever and illuminate the minds of many endlessly.Often these words become an element of entertainment for the reader.Following this concept, The Literary Club has brought you an ongoing series of short stories “Kuch Kisse Kuch Kahaniyan..” where the students revealed the writer, hidden somewhere deep inside them.Uptil now, we have got a bunch of short stories manifesting different emotions… Different climaxes and different characters.. ",category:"Short Story Writing",time:"Ongoing",title:"Kuch Kisse Kuch Kahaniyan..",hostman:"Shaivya Yadav",platform:"Online Event"}

];
export default Details;